version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: service-queue-server
    command: yarn dev
    environment:
      - MORGAN_LOGGER=true
      - MORGAN_BODY_LOGGER=true
      - EXPRESS_DEV_LOGGER=true
      - LOGGER_LEVEL=debug
      - PORT=3333
      - NODE_ENV=dev
      - MONGO_PORT=27017
      - MONGO_HOST=service-queue-mongo
      - FRANKFURTER_URL=https://api.frankfurter.app

    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - mongo
    networks:
      - backend-network
  mongo:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    container_name: service-queue-mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - '/mongodb_data:/bitnami/mongodb'
    networks:
      - backend-network

volumes:
  mongodb_data:
    driver: local

networks:
  backend-network:
    driver: bridge
